name: keep_py310
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - python=3.10.19
  - setuptools=80.9.0
  - sqlite=3.50.2
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - astunparse==1.6.3
      - attrs==25.4.0
      - av==16.0.1
      - basicsr==1.4.2
      - beautifulsoup4==4.14.2
      - blinker==1.9.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - cython==3.2.1
      - deepface==0.0.95
      - diffusers==0.11.0
      - dlib-bin==19.24.6
      - easydict==1.13
      - einops==0.8.1
      - facexlib==0.3.0
      - ffmpeg-python==0.2.0
      - filelock==3.19.1
      - filterpy==1.4.5
      - fire==0.7.1
      - flask==3.1.2
      - flask-cors==6.0.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - future==1.0.0
      - gast==0.6.0
      - gdown==5.2.0
      - gfpgan==1.3.8
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - gunicorn==23.0.0
      - h5py==3.15.1
      - huggingface-hub==0.25.1
      - idna==3.11
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - insightface==0.7.3
      - intel-openmp==2021.4.0
      - itsdangerous==2.2.0
      - jax==0.6.2
      - jaxlib==0.6.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - keras==3.12.0
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - libclang==18.1.1
      - llvmlite==0.45.1
      - lmdb==1.7.5
      - lpips==0.1.4
      - lz4==4.4.5
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - mediapipe==0.10.21
      - mkl==2021.4.0
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - mtcnn==1.0.0
      - namex==0.1.0
      - networkx==3.3
      - numba==0.62.1
      - numpy==1.26.4
      - onnx==1.19.1
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.8.1.78
      - opencv-python-headless==4.12.0.88
      - opt-einsum==3.4.0
      - optree==0.18.0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - pip==25.3
      - platformdirs==4.5.0
      - prettytable==3.17.0
      - protobuf==4.25.8
      - pycparser==2.23
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - realesrgan==0.3.0
      - regex==2025.11.3
      - requests==2.32.5
      - retina-face==0.0.17
      - rich==14.2.0
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentencepiece==0.2.1
      - simsimd==6.5.3
      - six==1.17.0
      - sounddevice==0.5.3
      - soupsieve==2.8
      - stringzilla==4.2.3
      - sympy==1.14.0
      - tb-nightly==2.21.0a20251023
      - tbb==2021.11.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.1
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.2.0
      - tf-keras==2.19.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==0.9.2
      - tomli==2.3.0
      - torch==2.0.1+cu118
      - torchaudio==2.0.2+cu118
      - torchvision==0.15.2+cu118
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - werkzeug==3.1.3
      - wrapt==2.0.1
      - yapf==0.43.0
      - zipp==3.23.0
prefix: C:\Users\hcwon\miniconda3\envs\keep_py310
